# Generated by Django 4.1.7 on 2023-07-15 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0018_chart_of_account_upload'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chart_of_account_upload',
            name='account',
        ),
        migrations.RemoveField(
            model_name='chart_of_account_upload',
            name='user',
        ),
        migrations.DeleteModel(
            name='Chart_of_Account',
        ),
        migrations.DeleteModel(
            name='Chart_of_Account_Upload',
        ),
    ]
